version: "3.9"

services:
  api:
    build: ./backend
    container_name: lanedu_labs_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://lanedu:lanedu_pass@db:5432/lanedu_labs
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app:ro

  db:
    image: postgres:16
    container_name: lanedu_labs_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lanedu
      POSTGRES_PASSWORD: lanedu_pass
      POSTGRES_DB: lanedu_labs
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
